// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class Budget
{
    public string Id { get; set; }

    public string CustomerId { get; set; }

    public string TransactionCategoryId { get; set; }

    public double Amount { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool? Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual TransactionCategory TransactionCategory { get; set; }
}