// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repository.Models;

public partial class Customer
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Password { get; set; }

    public string Address { get; set; }

    public DateTime Dob { get; set; }

    public string PassCode { get; set; }

    public bool Status { get; set; }

    public virtual Wallet IdNavigation { get; set; }

    public virtual ICollection<RecurringTransaction> RecurringTransactions { get; set; } = new List<RecurringTransaction>();

    public virtual ICollection<SavingGoal> SavingGoals { get; set; } = new List<SavingGoal>();

    public virtual ICollection<Transation> Transations { get; set; } = new List<Transation>();
}