// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class CustomerTransactionCategory
{
    public string CustomerId { get; set; }

    public string TransactionCategoryId { get; set; }

    public double? Percent { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual TransactionCategory TransactionCategory { get; set; }
}