// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class Notification
{
    public string Id { get; set; }

    public string CustomerId { get; set; }

    public string Message { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsRead { get; set; }

    public virtual Customer Customer { get; set; }
}