// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class RecurringTransaction
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int TransactionTypeId { get; set; }

    public double Amount { get; set; }

    public int Frequency { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Note { get; set; }

    public bool Status { get; set; }

    public int CustomerId { get; set; }

    public virtual Customer Customer { get; set; }
}