// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repository.Models;

public partial class SavingTransaction
{
    public int Id { get; set; }

    public double Amount { get; set; }

    public bool IsDeposit { get; set; }

    public DateTime? Time { get; set; }

    public string Note { get; set; }

    public int SavingGoalId { get; set; }

    public virtual SavingGoal SavingGoal { get; set; }
}