// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class SavingGoal
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public string Title { get; set; }

    public double TargetAmount { get; set; }

    public double CurrentAmount { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<SavingTransaction> SavingTransactions { get; set; } = new List<SavingTransaction>();
}