// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class Transaction
{
    public string Id { get; set; }

    public string Code { get; set; }

    public double Money { get; set; }

    public string TransactionCategoryId { get; set; }

    public bool? IsIncome { get; set; }

    public DateTime Time { get; set; }

    public string CustomerId { get; set; }

    public string WalletId { get; set; }

    public string CurrencyId { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual TransactionCategory TransactionCategory { get; set; }

    public virtual Wallet Wallet { get; set; }
}