// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repository.Models;

public partial class Transation
{
    public int Id { get; set; }

    public string Code { get; set; }

    public double Money { get; set; }

    public int TransactionTypeId { get; set; }

    public bool? IsIncome { get; set; }

    public DateTime Time { get; set; }

    public int CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Wallet CustomerNavigation { get; set; }

    public virtual TransationType TransactionType { get; set; }
}