// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class TransactionCategory
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string TransactionTypeId { get; set; }

    public string CustomerId { get; set; }

    public string IconId { get; set; }

    public virtual ICollection<Budget> Budgets { get; set; } = new List<Budget>();

    public virtual Customer Customer { get; set; }

    public virtual ICollection<CustomerTransactionCategory> CustomerTransactionCategories { get; set; } = new List<CustomerTransactionCategory>();

    public virtual Icon Icon { get; set; }

    public virtual ICollection<RecurringTransaction> RecurringTransactions { get; set; } = new List<RecurringTransaction>();

    public virtual TransactionType TransactionType { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}