// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class TransactionType
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<TransactionCategory> TransactionCategories { get; set; } = new List<TransactionCategory>();
}