// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repository.Models;

public partial class Wallet
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public double Money { get; set; }

    public bool Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<RecurringTransaction> RecurringTransactions { get; set; } = new List<RecurringTransaction>();

    public virtual ICollection<Transation> Transations { get; set; } = new List<Transation>();
}