// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MoneyFlow.Repositories.Models;

public partial class Wallet
{
    public string Id { get; set; }

    public string CustomerId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string AccountNumber { get; set; }

    public double Balance { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool? Status { get; set; }

    public string CurrencyId { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}